### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by mmweru** [mmweru/Learn2Earn#2]
Make the website responsive to all screen sizes

**Comment by rovertrack** [comment]
can i  go ahead with this issue 
if i can assign me

**Comment by mmweru** [comment]
> can i go ahead with this issue if i can assign me

@rovertrack  please feel free to contribute

**Comment by mmweru** [comment]
> can i go ahead with this issue if i can assign me

Issue is fixed, thank you for helping.
